# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoMeter_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 511, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_DMM = QtWidgets.QWidget()
        self.tab_DMM.setObjectName("tab_DMM")
        self.groupBox_DMM_mode = QtWidgets.QGroupBox(self.tab_DMM)
        self.groupBox_DMM_mode.setGeometry(QtCore.QRect(20, 150, 211, 121))
        self.groupBox_DMM_mode.setObjectName("groupBox_DMM_mode")
        self.radioButton_DMM_VOLT = QtWidgets.QRadioButton(self.groupBox_DMM_mode)
        self.radioButton_DMM_VOLT.setGeometry(QtCore.QRect(10, 30, 105, 26))
        self.radioButton_DMM_VOLT.setChecked(True)
        self.radioButton_DMM_VOLT.setObjectName("radioButton_DMM_VOLT")
        self.radioButton_DMM_CURR = QtWidgets.QRadioButton(self.groupBox_DMM_mode)
        self.radioButton_DMM_CURR.setGeometry(QtCore.QRect(10, 60, 105, 26))
        self.radioButton_DMM_CURR.setObjectName("radioButton_DMM_CURR")
        self.radioButton_POW = QtWidgets.QRadioButton(self.groupBox_DMM_mode)
        self.radioButton_POW.setEnabled(False)
        self.radioButton_POW.setGeometry(QtCore.QRect(10, 90, 105, 26))
        self.radioButton_POW.setObjectName("radioButton_POW")
        self.pushButton_DMM_start = QtWidgets.QPushButton(self.tab_DMM)
        self.pushButton_DMM_start.setEnabled(True)
        self.pushButton_DMM_start.setGeometry(QtCore.QRect(260, 380, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_DMM_start.setPalette(palette)
        self.pushButton_DMM_start.setObjectName("pushButton_DMM_start")
        self.pushButton_DMM_stop = QtWidgets.QPushButton(self.tab_DMM)
        self.pushButton_DMM_stop.setEnabled(False)
        self.pushButton_DMM_stop.setGeometry(QtCore.QRect(380, 380, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_DMM_stop.setPalette(palette)
        self.pushButton_DMM_stop.setObjectName("pushButton_DMM_stop")
        self.label_DMM_measValue = QtWidgets.QLabel(self.tab_DMM)
        self.label_DMM_measValue.setEnabled(False)
        self.label_DMM_measValue.setGeometry(QtCore.QRect(20, 20, 471, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_DMM_measValue.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.label_DMM_measValue.setFont(font)
        self.label_DMM_measValue.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_DMM_measValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_DMM_measValue.setLineWidth(1)
        self.label_DMM_measValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DMM_measValue.setObjectName("label_DMM_measValue")
        self.tabWidget.addTab(self.tab_DMM, "")
        self.tab_FGEN = QtWidgets.QWidget()
        self.tab_FGEN.setObjectName("tab_FGEN")
        self.label_FGEN_Freq = QtWidgets.QLabel(self.tab_FGEN)
        self.label_FGEN_Freq.setEnabled(False)
        self.label_FGEN_Freq.setGeometry(QtCore.QRect(20, 30, 341, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_FGEN_Freq.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_FGEN_Freq.setFont(font)
        self.label_FGEN_Freq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_FGEN_Freq.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_FGEN_Freq.setLineWidth(1)
        self.label_FGEN_Freq.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FGEN_Freq.setObjectName("label_FGEN_Freq")
        self.pushButton_FGEN_stop = QtWidgets.QPushButton(self.tab_FGEN)
        self.pushButton_FGEN_stop.setEnabled(False)
        self.pushButton_FGEN_stop.setGeometry(QtCore.QRect(380, 380, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_FGEN_stop.setPalette(palette)
        self.pushButton_FGEN_stop.setObjectName("pushButton_FGEN_stop")
        self.pushButton_FGEN_start = QtWidgets.QPushButton(self.tab_FGEN)
        self.pushButton_FGEN_start.setEnabled(True)
        self.pushButton_FGEN_start.setGeometry(QtCore.QRect(260, 380, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_FGEN_start.setPalette(palette)
        self.pushButton_FGEN_start.setObjectName("pushButton_FGEN_start")
        self.dial_FGEN_Freq = QtWidgets.QDial(self.tab_FGEN)
        self.dial_FGEN_Freq.setGeometry(QtCore.QRect(400, 20, 81, 81))
        self.dial_FGEN_Freq.setWrapping(True)
        self.dial_FGEN_Freq.setObjectName("dial_FGEN_Freq")
        self.label_FGEN_Amp = QtWidgets.QLabel(self.tab_FGEN)
        self.label_FGEN_Amp.setEnabled(False)
        self.label_FGEN_Amp.setGeometry(QtCore.QRect(20, 120, 341, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_FGEN_Amp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_FGEN_Amp.setFont(font)
        self.label_FGEN_Amp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_FGEN_Amp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_FGEN_Amp.setLineWidth(1)
        self.label_FGEN_Amp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FGEN_Amp.setObjectName("label_FGEN_Amp")
        self.dial_FGEN_Amp = QtWidgets.QDial(self.tab_FGEN)
        self.dial_FGEN_Amp.setGeometry(QtCore.QRect(400, 110, 81, 81))
        self.dial_FGEN_Amp.setMinimum(0)
        self.dial_FGEN_Amp.setMaximum(99)
        self.dial_FGEN_Amp.setWrapping(True)
        self.dial_FGEN_Amp.setObjectName("dial_FGEN_Amp")
        self.label_FGEN_Offset = QtWidgets.QLabel(self.tab_FGEN)
        self.label_FGEN_Offset.setEnabled(False)
        self.label_FGEN_Offset.setGeometry(QtCore.QRect(20, 220, 341, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_FGEN_Offset.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_FGEN_Offset.setFont(font)
        self.label_FGEN_Offset.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_FGEN_Offset.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_FGEN_Offset.setLineWidth(1)
        self.label_FGEN_Offset.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FGEN_Offset.setObjectName("label_FGEN_Offset")
        self.dial_FGEN_Offset = QtWidgets.QDial(self.tab_FGEN)
        self.dial_FGEN_Offset.setGeometry(QtCore.QRect(400, 210, 81, 81))
        self.dial_FGEN_Offset.setMinimum(0)
        self.dial_FGEN_Offset.setMaximum(99)
        self.dial_FGEN_Offset.setWrapping(True)
        self.dial_FGEN_Offset.setObjectName("dial_FGEN_Offset")
        self.label_freq = QtWidgets.QLabel(self.tab_FGEN)
        self.label_freq.setGeometry(QtCore.QRect(20, 10, 91, 20))
        self.label_freq.setObjectName("label_freq")
        self.label_amp = QtWidgets.QLabel(self.tab_FGEN)
        self.label_amp.setGeometry(QtCore.QRect(20, 100, 121, 20))
        self.label_amp.setObjectName("label_amp")
        self.label_offs = QtWidgets.QLabel(self.tab_FGEN)
        self.label_offs.setGeometry(QtCore.QRect(20, 200, 121, 20))
        self.label_offs.setObjectName("label_offs")
        self.groupBox_waveform = QtWidgets.QGroupBox(self.tab_FGEN)
        self.groupBox_waveform.setGeometry(QtCore.QRect(20, 300, 211, 121))
        self.groupBox_waveform.setObjectName("groupBox_waveform")
        self.radioButton_FGEN_Sine = QtWidgets.QRadioButton(self.groupBox_waveform)
        self.radioButton_FGEN_Sine.setGeometry(QtCore.QRect(10, 30, 105, 26))
        self.radioButton_FGEN_Sine.setChecked(True)
        self.radioButton_FGEN_Sine.setObjectName("radioButton_FGEN_Sine")
        self.radioButton_FGEN_Square = QtWidgets.QRadioButton(self.groupBox_waveform)
        self.radioButton_FGEN_Square.setGeometry(QtCore.QRect(10, 60, 105, 26))
        self.radioButton_FGEN_Square.setObjectName("radioButton_FGEN_Square")
        self.radioButton_FGEN_Triangle = QtWidgets.QRadioButton(self.groupBox_waveform)
        self.radioButton_FGEN_Triangle.setEnabled(False)
        self.radioButton_FGEN_Triangle.setGeometry(QtCore.QRect(10, 90, 105, 26))
        self.radioButton_FGEN_Triangle.setObjectName("radioButton_FGEN_Triangle")
        self.tabWidget.addTab(self.tab_FGEN, "")
        self.tab_DSO = QtWidgets.QWidget()
        self.tab_DSO.setEnabled(True)
        self.tab_DSO.setObjectName("tab_DSO")
        self.MplWidget = MplWidget(self.tab_DSO)
        self.MplWidget.setGeometry(QtCore.QRect(-1, -1, 511, 251))
        self.MplWidget.setObjectName("MplWidget")
        self.pushButton_DSO_start = QtWidgets.QPushButton(self.tab_DSO)
        self.pushButton_DSO_start.setEnabled(True)
        self.pushButton_DSO_start.setGeometry(QtCore.QRect(260, 380, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_DSO_start.setPalette(palette)
        self.pushButton_DSO_start.setObjectName("pushButton_DSO_start")
        self.pushButton_DSO_stop = QtWidgets.QPushButton(self.tab_DSO)
        self.pushButton_DSO_stop.setEnabled(False)
        self.pushButton_DSO_stop.setGeometry(QtCore.QRect(380, 380, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_DSO_stop.setPalette(palette)
        self.pushButton_DSO_stop.setObjectName("pushButton_DSO_stop")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_DSO)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 267, 391, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dial_DSO_pos = QtWidgets.QDial(self.gridLayoutWidget)
        self.dial_DSO_pos.setMinimum(0)
        self.dial_DSO_pos.setMaximum(100)
        self.dial_DSO_pos.setProperty("value", 50)
        self.dial_DSO_pos.setWrapping(True)
        self.dial_DSO_pos.setNotchesVisible(False)
        self.dial_DSO_pos.setObjectName("dial_DSO_pos")
        self.gridLayout.addWidget(self.dial_DSO_pos, 1, 2, 1, 1)
        self.label_pos = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_pos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pos.setObjectName("label_pos")
        self.gridLayout.addWidget(self.label_pos, 0, 2, 1, 1)
        self.dial_DSO_vert = QtWidgets.QDial(self.gridLayoutWidget)
        self.dial_DSO_vert.setMinimum(-7)
        self.dial_DSO_vert.setMaximum(3)
        self.dial_DSO_vert.setSingleStep(1)
        self.dial_DSO_vert.setProperty("value", -2)
        self.dial_DSO_vert.setNotchesVisible(True)
        self.dial_DSO_vert.setObjectName("dial_DSO_vert")
        self.gridLayout.addWidget(self.dial_DSO_vert, 1, 1, 1, 1)
        self.dial_DSO_hor = QtWidgets.QDial(self.gridLayoutWidget)
        self.dial_DSO_hor.setMinimum(-9)
        self.dial_DSO_hor.setMaximum(3)
        self.dial_DSO_hor.setProperty("value", -3)
        self.dial_DSO_hor.setNotchesVisible(True)
        self.dial_DSO_hor.setObjectName("dial_DSO_hor")
        self.gridLayout.addWidget(self.dial_DSO_hor, 1, 0, 1, 1)
        self.label_hor = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_hor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hor.setObjectName("label_hor")
        self.gridLayout.addWidget(self.label_hor, 0, 0, 1, 1)
        self.label_vert = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vert.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vert.setObjectName("label_vert")
        self.gridLayout.addWidget(self.label_vert, 0, 1, 1, 1)
        self.MplWidget.raise_()
        self.pushButton_DSO_stop.raise_()
        self.pushButton_DSO_start.raise_()
        self.gridLayoutWidget.raise_()
        self.tabWidget.addTab(self.tab_DSO, "")
        self.comboBox_device = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_device.setEnabled(True)
        self.comboBox_device.setGeometry(QtCore.QRect(10, 30, 311, 28))
        self.comboBox_device.setObjectName("comboBox_device")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 62, 20))
        self.label.setObjectName("label")
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(340, 30, 83, 28))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.pushButton_disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_disconnect.setEnabled(False)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(440, 30, 83, 28))
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CoMeter"))
        self.groupBox_DMM_mode.setTitle(_translate("MainWindow", "Measurement mode:"))
        self.radioButton_DMM_VOLT.setText(_translate("MainWindow", "&Voltage"))
        self.radioButton_DMM_CURR.setText(_translate("MainWindow", "&Current"))
        self.radioButton_POW.setText(_translate("MainWindow", "&Power"))
        self.pushButton_DMM_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_DMM_stop.setText(_translate("MainWindow", "Stop"))
        self.label_DMM_measValue.setText(_translate("MainWindow", "0.0000 V"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DMM), _translate("MainWindow", "DMM"))
        self.label_FGEN_Freq.setText(_translate("MainWindow", "10.000 Hz"))
        self.pushButton_FGEN_stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_FGEN_start.setText(_translate("MainWindow", "Start"))
        self.label_FGEN_Amp.setText(_translate("MainWindow", "2.000 V"))
        self.label_FGEN_Offset.setText(_translate("MainWindow", "0.000 V"))
        self.label_freq.setText(_translate("MainWindow", "Frequency:"))
        self.label_amp.setText(_translate("MainWindow", "Amplitude (P2P):"))
        self.label_offs.setText(_translate("MainWindow", "Offset:"))
        self.groupBox_waveform.setTitle(_translate("MainWindow", "Waveform:"))
        self.radioButton_FGEN_Sine.setText(_translate("MainWindow", "&Sine"))
        self.radioButton_FGEN_Square.setText(_translate("MainWindow", "S&quare"))
        self.radioButton_FGEN_Triangle.setText(_translate("MainWindow", "&Triangle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_FGEN), _translate("MainWindow", "FGEN"))
        self.pushButton_DSO_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_DSO_stop.setText(_translate("MainWindow", "Stop"))
        self.label_pos.setText(_translate("MainWindow", "Position:"))
        self.label_hor.setText(_translate("MainWindow", "Horizontal:"))
        self.label_vert.setText(_translate("MainWindow", "Vertical:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DSO), _translate("MainWindow", "DSO"))
        self.label.setText(_translate("MainWindow", "Device:"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "Disconnect"))

from mplwidget import MplWidget
